FROM node:20.9.0 as build

WORKDIR /app
COPY package*.json .

RUN npm ci
COPY . .
RUN npm build

FROM nginx:1.23.0-alpine
EXPOSE 4200
COPY nginx.conf /etc/nginx/nginx.conf
COPY --from=build /app/dist/busca-persona-free /usr/share/nginx/html